import { createCipheriv, createDecipheriv, createHmac, randomBytes } from "node:crypto";
export type SocialProvider = "meta" | "instagram" | "tiktok";
function key() { const raw=process.env.SOCIAL_TOKEN_ENCRYPTION_KEY || ""; const value=Buffer.from(raw,"base64"); if(value.length!==32) throw new Error("SOCIAL_TOKEN_ENCRYPTION_KEY must be a base64 encoded 32-byte key."); return value; }
export function seal(value:string) { const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key(),iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(x=>x.toString("base64url")).join("."); }
export function open(value:string) { const [a,b,c]=value.split(".");const decipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(a,"base64url"));decipher.setAuthTag(Buffer.from(b,"base64url"));return Buffer.concat([decipher.update(Buffer.from(c,"base64url")),decipher.final()]).toString("utf8"); }
export function stateFor(userId:string,provider:SocialProvider) { const payload=Buffer.from(JSON.stringify({userId,provider,expires:Date.now()+10*60_000,nonce:randomBytes(12).toString("hex")})).toString("base64url");const signature=createHmac("sha256",key()).update(payload).digest("base64url");return `${payload}.${signature}`; }
export function readState(value:string) { const dot=value.lastIndexOf(".");if(dot<1)throw new Error("Invalid state");const payload=value.slice(0,dot),signature=value.slice(dot+1);const expected=createHmac("sha256",key()).update(payload).digest("base64url");if(signature.length!==expected.length || !timingSafe(signature,expected))throw new Error("Invalid state");const result=JSON.parse(Buffer.from(payload,"base64url").toString());if(result.expires<Date.now() || !["meta","instagram","tiktok"].includes(result.provider))throw new Error("Expired state");return result as {userId:string;provider:SocialProvider}; }
function timingSafe(a:string,b:string){let mismatch=0;for(let i=0;i<a.length;i++)mismatch|=a.charCodeAt(i)^b.charCodeAt(i);return mismatch===0;}
export function appUrl(request:Request){return process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/,"") || new URL(request.url).origin;}
