import { NextResponse } from "next/server";
import { authorize } from "../../../lib/supabase/authorize";
import { appUrl, readState, seal } from "../../../lib/social";
type Saved={provider:"meta"|"instagram"|"tiktok";platform:"Facebook"|"Instagram"|"TikTok";account_id:string;account_name:string;token_ciphertext:string;metadata:Record<string,unknown>;expires_at:string|null};
export async function GET(request:Request){const home=appUrl(request);const url=new URL(request.url);const auth=await authorize(request);if(auth.response)return NextResponse.redirect(`${home}/login`);try{if(url.searchParams.get("error"))throw new Error(url.searchParams.get("error_description")||"Social authorization was cancelled.");const code=url.searchParams.get("code"),state=url.searchParams.get("state");if(!code||!state)throw new Error("The provider returned an incomplete authorization response.");const checked=readState(state);if(checked.userId!==auth.user.id)throw new Error("The signed-in account changed during connection.");const callback=`${home}/auth/social/callback`;let rows:Saved[]=[];
if(checked.provider==="meta"){const tokenUrl=new URL("https://graph.facebook.com/v23.0/oauth/access_token");tokenUrl.search=new URLSearchParams({client_id:process.env.META_APP_ID!,client_secret:process.env.META_APP_SECRET!,redirect_uri:callback,code}).toString();const token=await fetch(tokenUrl,{signal:AbortSignal.timeout(15000)}).then(r=>r.json());if(!token.access_token)throw new Error("Meta did not issue an access token.");const accounts=await fetch(`https://graph.facebook.com/v23.0/me/accounts?fields=id,name,access_token&access_token=${encodeURIComponent(token.access_token)}`,{signal:AbortSignal.timeout(15000)}).then(r=>r.json());if(!Array.isArray(accounts.data)||!accounts.data.length)throw new Error("No Facebook Pages were found. Connect a profile that manages a Page.");for(const page of accounts.data)rows.push({provider:"meta",platform:"Facebook",account_id:String(page.id),account_name:String(page.name||"Facebook Page"),token_ciphertext:seal(page.access_token),metadata:{page_id:page.id},expires_at:null});}
else if(checked.provider==="instagram"){const form=new URLSearchParams({client_id:process.env.INSTAGRAM_APP_ID!,client_secret:process.env.INSTAGRAM_APP_SECRET!,grant_type:"authorization_code",redirect_uri:callback,code});const shortToken=await fetch("https://api.instagram.com/oauth/access_token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form,signal:AbortSignal.timeout(15000)}).then(r=>r.json());if(!shortToken.access_token||!shortToken.user_id)throw new Error("Instagram did not issue an access token.");const longUrl=new URL("https://graph.instagram.com/access_token");longUrl.search=new URLSearchParams({grant_type:"ig_exchange_token",client_secret:process.env.INSTAGRAM_APP_SECRET!,access_token:shortToken.access_token}).toString();const longToken=await fetch(longUrl,{signal:AbortSignal.timeout(15000)}).then(r=>r.json());const accessToken=String(longToken.access_token||shortToken.access_token);const info=await fetch(`https://graph.instagram.com/me?fields=id,user_id,username,name&access_token=${encodeURIComponent(accessToken)}`,{signal:AbortSignal.timeout(15000)}).then(r=>r.json());const accountId=String(info.user_id||info.id||shortToken.user_id);if(!accountId)throw new Error("Instagram account details were unavailable.");rows=[{provider:"instagram",platform:"Instagram",account_id:accountId,account_name:String(info.username||info.name||"Instagram account"),token_ciphertext:seal(accessToken),metadata:{scope:"instagram_business_basic,instagram_business_content_publish"},expires_at:new Date(Date.now()+Number(longToken.expires_in||5184000)*1000).toISOString()}];}
else {const form=new URLSearchParams({client_key:process.env.TIKTOK_CLIENT_KEY!,client_secret:process.env.TIKTOK_CLIENT_SECRET!,code,grant_type:"authorization_code",redirect_uri:callback});const token=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form,signal:AbortSignal.timeout(15000)}).then(r=>r.json());if(!token.access_token||!token.open_id)throw new Error("TikTok did not issue an access token.");const info=await fetch("https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name,avatar_url",{headers:{Authorization:`Bearer ${token.access_token}`},signal:AbortSignal.timeout(15000)}).then(r=>r.json());rows=[{provider:"tiktok",platform:"TikTok",account_id:String(token.open_id),account_name:String(info?.data?.user?.display_name||"TikTok account"),token_ciphertext:seal(token.access_token),metadata:{refresh_token:seal(token.refresh_token||""),scope:token.scope},expires_at:new Date(Date.now()+Number(token.expires_in||86400)*1000).toISOString()}];}
for(const row of rows){const {error}=await auth.supabase.from("social_connections").upsert({user_id:auth.user.id,...row},{onConflict:"user_id,platform,account_id"});if(error)throw new Error("The account was authorized but could not be saved. Run the social migration.");}return NextResponse.redirect(`${home}/app?social_connected=1`);
}catch(error){return NextResponse.redirect(`${home}/app?social_error=${encodeURIComponent(error instanceof Error?error.message:"Unable to connect social account.")}`);}}
