import {NextResponse} from "next/server";
import {authorize} from "../../../lib/supabase/authorize";
import {ASSET_BUCKET,ownPath} from "../../../lib/brand-media";
import {open} from "../../../lib/social";
import {validContent} from "../../../lib/validation";
import {destinations,type ContentItem} from "../../../types/marketpilot";

export const runtime="nodejs";export const maxDuration=60;
const headers={"Cache-Control":"private, no-store"};
const caption=(content:ContentItem,max:number)=>[content.hook,content.body,content.cta,content.hashtags.join(" ")].filter(Boolean).join("\n\n").slice(0,max);
async function graph(url:string,init?:RequestInit){const response=await fetch(url,{...init,signal:AbortSignal.timeout(25000)});const data=await response.json();if(!response.ok||data?.error)throw new Error(String(data?.error?.message||"The social platform rejected this post.").slice(0,240));return data;}

export async function POST(request:Request){const auth=await authorize(request);if(auth.response)return auth.response;let content:ContentItem;try{const raw=await request.text();if(raw.length>50000)return NextResponse.json({error:"Post is too large."},{status:413,headers});content=JSON.parse(raw)?.content;}catch{return NextResponse.json({error:"Invalid publishing request."},{status:400,headers});}
 if(!content||!validContent(content)||content.status!=="Approved")return NextResponse.json({error:"Approve this post before publishing."},{status:400,headers});
 const requested=destinations(content);const supported=requested.filter(p=>p==="Facebook"||p==="Instagram");const unsupported=requested.filter(p=>p!=="Facebook"&&p!=="Instagram");if(unsupported.length)return NextResponse.json({error:`Automatic publishing is not ready for ${unsupported.join(", ")}. Remove those destinations or publish them manually.`},{status:400,headers});
 const [{data:connections,error},{data:published,error:publicationError}]=await Promise.all([auth.supabase.from("social_connections").select("provider,platform,account_id,token_ciphertext").eq("user_id",auth.user.id).in("platform",supported),auth.supabase.from("social_publications").select("platform,account_id,external_id").eq("user_id",auth.user.id).eq("content_id",content.id)]);if(error)return NextResponse.json({error:"Unable to read connected accounts."},{status:503,headers});if(publicationError)return NextResponse.json({error:"Run the social publications migration before publishing."},{status:503,headers});
 let imageUrl="";if(content.graphicPath){if(!ownPath(content.graphicPath,auth.user.id))return NextResponse.json({error:"The attached graphic does not belong to this account."},{status:400,headers});const {data,error}=await auth.supabase.storage.from(ASSET_BUCKET).createSignedUrl(content.graphicPath,900);if(error||!data?.signedUrl)return NextResponse.json({error:"Unable to prepare the attached graphic for publishing."},{status:503,headers});imageUrl=data.signedUrl;}
 const results:{platform:string;accountId:string;externalId:string;alreadyPublished?:boolean}[]=[];
 try{for(const platform of supported){const connection=connections?.find(c=>c.platform===platform);if(!connection)return NextResponse.json({error:`Connect ${platform} before publishing.`},{status:400,headers});const token=open(connection.token_ciphertext);
   const previous=published?.find(p=>p.platform===platform&&p.account_id===connection.account_id);if(previous){results.push({platform,accountId:connection.account_id,externalId:previous.external_id,alreadyPublished:true});continue;}
   let externalId="";if(platform==="Facebook"){const endpoint=imageUrl?`https://graph.facebook.com/v23.0/${encodeURIComponent(connection.account_id)}/photos`:`https://graph.facebook.com/v23.0/${encodeURIComponent(connection.account_id)}/feed`;const form=new URLSearchParams({access_token:token});if(imageUrl){form.set("url",imageUrl);form.set("caption",caption(content,60000));}else form.set("message",caption(content,60000));const data=await graph(endpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form});externalId=String(data.post_id||data.id);}
   else {if(!imageUrl)return NextResponse.json({error:"Instagram requires an attached graphic. Create or upload one before publishing."},{status:400,headers});const create=new URLSearchParams({image_url:imageUrl,caption:caption(content,2200),access_token:token});const container=await graph(`https://graph.instagram.com/v23.0/${encodeURIComponent(connection.account_id)}/media`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:create});if(!container.id)throw new Error("Instagram did not create a media container.");const publish=new URLSearchParams({creation_id:String(container.id),access_token:token});const data=await graph(`https://graph.instagram.com/v23.0/${encodeURIComponent(connection.account_id)}/media_publish`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:publish});externalId=String(data.id);}
   const {error:saveError}=await auth.supabase.from("social_publications").insert({user_id:auth.user.id,content_id:content.id,platform,account_id:connection.account_id,external_id:externalId});if(saveError)throw new Error(`${platform} published, but confirmation could not be saved. Do not retry until you check the social account.`);results.push({platform,accountId:connection.account_id,externalId});
 }return NextResponse.json({ok:true,results},{headers});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Publishing failed."},{status:502,headers});}}
