"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import { Loader2, Sparkles, Trash2, Upload } from "lucide-react";
import type { BusinessProfile, Graphic } from "./types/marketpilot";
const url=(path:string)=>`/api/media?path=${encodeURIComponent(path)}`;
export default function GraphicsStudio({profile,userId,seed="",onUse}:{profile:BusinessProfile;userId:string;seed?:string;onUse?:(path:string)=>void}) {
 const [graphics,setGraphics]=useState<Graphic[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[configured,setConfigured]=useState<boolean|null>(null);
 const [prompt,setPrompt]=useState(seed),[headline,setHeadline]=useState(""),[description,setDescription]=useState(""),[cta,setCta]=useState(""),[kind,setKind]=useState<Graphic["kind"]>("post"),[format,setFormat]=useState<Graphic["format"]>("square");
 useEffect(()=>{const controller=new AbortController();fetch("/api/graphics",{headers:{"x-marketpilot-user":userId},signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok) throw new Error(d.error);setGraphics(d.graphics);setConfigured(d.configured);}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[userId]);
 async function generate(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/graphics",{method:"POST",headers:{"Content-Type":"application/json","x-marketpilot-user":userId},body:JSON.stringify({profile,prompt,headline,description,cta,kind,format}),signal:AbortSignal.timeout(65000)});const d=await r.json();if(!r.ok)throw new Error(d.error);setGraphics(g=>[d.graphic,...g]);if(d.copy){setHeadline(d.copy.headline);setDescription(d.copy.description);setCta(d.copy.cta);}setMessage(d.graphic.demo?"Demo template saved.":"Your branded graphic is ready.");}catch(e){setMessage(e instanceof Error?e.message:"Graphics generation failed.");}finally{setBusy(false);}}
 async function uploadArtwork(file?:File){if(!file)return;if(file.size>10000000){setMessage("Use an image below 10 MB.");return;}setUploading(true);setMessage("");try{const form=new FormData();form.set("file",file);const r=await fetch("/api/graphics/upload",{method:"POST",headers:{"x-marketpilot-user":userId},body:form,signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw new Error(d.error);setGraphics(g=>[d.graphic,...g]);if(onUse){onUse(d.graphic.path);return;}setMessage("Artwork uploaded to your graphics library.");}catch(e){setMessage(e instanceof Error?e.message:"Artwork upload failed.");}finally{setUploading(false);}}
 async function remove(graphic:Graphic){if(!confirm("Permanently delete this graphic? Download a copy first if you need it."))return;try{const r=await fetch(`/api/graphics?id=${graphic.id}`,{method:"DELETE",headers:{"x-marketpilot-user":userId}});const d=await r.json();if(!r.ok)throw new Error(d.error);setGraphics(g=>g.filter(x=>x.id!==graphic.id));}catch(e){setMessage(e instanceof Error?e.message:"Delete failed.");}}
 return <section className="graphics-layout"><form className="card form-card" onSubmit={generate}><p className="eyebrow">CREATIVE STUDIO</p><h2>Create branded artwork.</h2>
 <div className="two-col"><label className="field"><span>Creative type</span><select value={kind} onChange={e=>setKind(e.target.value as Graphic["kind"])}><option value="post">Social post</option><option value="ad">Advertisement</option><option value="banner">Banner</option></select></label><label className="field"><span>Size</span><select value={format} onChange={e=>setFormat(e.target.value as Graphic["format"])}><option value="square">Square - 1080 - 1080</option><option value="portrait">Portrait - 1080 - 1350</option><option value="landscape">Landscape - 1600 - 900</option></select></label></div>
 <label className="field"><span>Creative brief</span><textarea required maxLength={4000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the offer, imagery and style you want."/></label><label className="field"><span>Headline</span><input maxLength={100} value={headline} onChange={e=>setHeadline(e.target.value)} placeholder="Optional — AI will create it"/></label><label className="field"><span>Short supporting description</span><input maxLength={160} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional — AI will create it"/></label><label className="field"><span>Call to action</span><input maxLength={60} value={cta} onChange={e=>setCta(e.target.value)} placeholder="Optional — AI will create it"/></label>
 {(profile.name==="MarketPilot Studio"||!profile.name.trim())&&<p className="auth-message" role="alert">Complete your business profile first.</p>}{configured===false&&<p className="auth-message" role="alert">Image generation is unavailable. You can upload finished artwork instead.</p>}<button className="primary wide" disabled={busy||configured===false||profile.name==="MarketPilot Studio"||!profile.name.trim()}>{busy?<Loader2 className="spin" size={18}/>:<Sparkles size={18}/>} {busy?"Creating...":"Generate graphic"}</button>{message&&<p role="status" className="auth-message">{message}</p>}</form>
 <div><div className="section-head"><div><h3>Saved graphics</h3><p className="muted">Upload finished artwork when you do not want to generate it. PNG, JPEG or WebP, up to 10 MB.</p></div><label className="chip"><Upload size={16}/>{uploading?"Uploading...":"Upload artwork"}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{void uploadArtwork(e.target.files?.[0]);e.target.value="";}}/></label></div>{!graphics.length&&<div className="card empty"><p>Your generated or uploaded graphics will appear here.</p></div>}<div className="graphics-grid">{graphics.map(g=><article className="card graphic-card" key={g.id}><Image src={url(g.path)} alt={g.headline || "Business graphic"} width={g.format==="landscape"?1600:1080} height={g.format==="portrait"?1350:g.format==="landscape"?900:1080} unoptimized/><strong>{g.headline}</strong><small>{g.kind} - {g.format}{g.demo?" - Demo":""}</small><div className="chips">{onUse&&<button className="primary compact" onClick={()=>onUse(g.path)}>Use for selected post</button>}<a className="chip" href={`${url(g.path)}&download=1`}>Download PNG</a><button className="icon-btn danger" title="Delete graphic" onClick={()=>remove(g)}><Trash2 size={17}/></button></div></article>)}</div></div></section>;
}
export function BrandAssets({profile,setProfile,userId}:{profile:BusinessProfile;setProfile:(p:BusinessProfile)=>void;userId:string}) {
 const [busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function upload(file:File|undefined,isLogo:boolean){if(!file)return;if(file.size>2000000){setMessage("Use an image below 2 MB.");return;}setBusy(true);setMessage("");try{const form=new FormData();form.set("file",file);const r=await fetch("/api/media",{method:"POST",headers:{"x-marketpilot-user":userId},body:form,signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw new Error(d.error);setProfile(isLogo?{...profile,logoPath:d.path}:{...profile,referencePaths:[...(profile.referencePaths || []),d.path]});setMessage("Image uploaded. Profile changes sync automatically.");}catch(e){setMessage(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false);}}
 return <fieldset className="brand-assets"><legend>Brand images</legend><p className="muted">Upload your logo and up to five product or brand reference images. PNG, JPEG or WebP, up to 2 MB each.</p><div className="brand-previews">{profile.logoPath&&<div><Image src={url(profile.logoPath)} alt="Business logo" width={160} height={120} unoptimized/><button type="button" className="text-btn" disabled={busy} onClick={()=>setProfile({...profile,logoPath:""})}>Remove logo</button></div>}{profile.referencePaths?.map(path=><div key={path}><Image src={url(path)} alt="Brand reference" width={160} height={120} unoptimized/><button type="button" className="text-btn" disabled={busy} onClick={()=>setProfile({...profile,referencePaths:profile.referencePaths?.filter(p=>p!==path)})}>Remove reference</button></div>)}</div><label className="field"><span>Upload logo</span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files?.[0],true);e.target.value="";}}/></label><label className="field"><span>Upload reference image</span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||(profile.referencePaths?.length || 0)>=5} onChange={e=>{void upload(e.target.files?.[0],false);e.target.value="";}}/></label>{busy&&<p role="status">Uploading...</p>}{message&&<p role="status">{message}</p>}</fieldset>;
}
