"use client";
import { useCallback,useEffect,useState } from "react";
import { Link2,Loader2,RefreshCw,Unlink } from "lucide-react";
type Connection={id:string;provider:string;platform:string;account_id:string;account_name:string;expires_at:string|null;updated_at:string};
export default function SocialConnections({userId}:{userId:string}){const [connections,setConnections]=useState<Connection[]>([]),[configured,setConfigured]=useState({meta:false,tiktok:false}),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/social/connections",{headers:{"x-marketpilot-user":userId},cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setConnections(d.connections);setConfigured(d.configured);const q=new URLSearchParams(location.search);if(q.get("social_connected"))setMessage("Social account connected.");if(q.get("social_error"))setMessage(q.get("social_error")!);if(q.has("social_connected")||q.has("social_error"))history.replaceState({},"",location.pathname);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load connections.");}finally{setLoading(false);}},[userId]);
useEffect(()=>{queueMicrotask(()=>void load());},[load]);
async function disconnect(id:string){if(!confirm("Disconnect this social account from MarketPilot? Existing posts are not deleted."))return;const r=await fetch(`/api/social/connections?id=${encodeURIComponent(id)}`,{method:"DELETE",headers:{"x-marketpilot-user":userId}});const d=await r.json();if(!r.ok){setMessage(d.error);return;}setConnections(c=>c.filter(x=>x.id!==id));setMessage("Account disconnected.");}
const group=(platform:string)=>connections.filter(c=>c.platform===platform);
const providers:{platform:string;provider:"meta"|"tiktok"|null}[]=[{platform:"Facebook",provider:"meta"},{platform:"Instagram",provider:"meta"},{platform:"TikTok",provider:"tiktok"},{platform:"LinkedIn",provider:null},{platform:"Pinterest",provider:null},{platform:"X",provider:null}];
return <section className="connections-page"><div className="card form-card"><p className="eyebrow">SOCIAL ACCOUNTS</p><h2>Connect your channels.</h2>{message&&<p className="auth-message" role="status">{message}</p>}{loading&&<p><Loader2 className="spin" size={18}/> Loading...</p>}
{providers.map(({platform,provider})=>{const available=provider?configured[provider]:false;return <div className="connection-row" key={platform}><div><strong>{platform}</strong>{group(platform).length?<small>{group(platform).map(x=>x.account_name).join(", ")}</small>:<small>{provider?"Not connected":"Integration coming soon"}</small>}</div>{group(platform).map(c=><button key={c.id} className="icon-btn danger" title={`Disconnect ${c.account_name}`} onClick={()=>disconnect(c.id)}><Unlink size={17}/></button>)}{!group(platform).length&&provider&&<a className={available?"primary compact":"chip disabled"} aria-disabled={!available} href={available?`/api/social/connect/${provider}`:undefined}><Link2 size={16}/>Connect</a>}</div>})}
<button className="chip" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button></div></section>}
